fix(playlists + albums): add a check that makes sure the playlist track isn't null
Solaris9/erela.js-spotify pull request #22
Opened 2021-07-24 08:00 UTC by ColdtQ

title^ 

Adds a check that makes sure a track isnt null in a album/playlist, if a single track was null, it would cause the whole playlist to not load. This basically ignores the track loading if its null/undefined

2021-07-24 08:01 UTC, ColdtQ commented
The axios commit was from an earlier PR. As of now i've removed the axios and switched it to petitio in the latest change. The first commit can be ignored.

2021-07-24 20:31 UTC, Strandxo commented
I'll have a look at this later today.

2021-07-25 19:25 UTC, Anish-Shobith reviewed
I would suggest making a function because its being used in multiple places
```ts
type Nullish = null | undefined;

function filterNullOrUndefined(value: unknown): value is Nullish {
	return value !== undefined || value !== null;
}
```

2021-07-25 19:26 UTC, Anish-Shobith commented on src/plugin.ts
> +        const tracks = album.tracks.items.filter((item) => item !== undefined || item !== null).map(item => Spotify.convertToUnresolved(item));
```ts
const tracks = album.tracks.items.filter(filterNullOrUndefined).map(item => Spotify.convertToUnresolved(item));
```

2021-07-25 19:28 UTC, Anish-Shobith commented on src/plugin.ts
> +        const tracks = playlist.tracks.items.filter((item) =>
```ts
const tracks = playlist.tracks.items.filter(filterNullOrUndefined).map(item => Spotify.convertToUnresolved(item.track));
```

2021-07-25 19:29 UTC, Anish-Shobith commented on src/plugin.ts
> +            tracks.push(...nextPage.items.filter((item) =>
```ts
tracks.push(...nextPage.items.filter(filterNullOrUndefined).map(item => Spotify.convertToUnresolved(item.track)));
```

2021-07-25 19:29 UTC, Anish-Shobith requested changes

2021-07-25 19:29 UTC, Anish-Shobith commented on src/plugin.ts
> +            tracks.push(...nextPage.items.filter((item) => item !== undefined || item !== null).map(item => Spotify.convertToUnresolved(item)));
```ts
tracks.push(...nextPage.items.filter(filterNullOrUndefined).map(item => Spotify.convertToUnresolved(item)));
```

2021-07-25 23:32 UTC, ColdtQ reviewed
I've revised the code to use a function over repeating .filter()

2021-08-05 23:26 UTC, ColdtQ commented
Rewrote to use the function @Anish-Shobith suggested

2021-08-20 21:00 UTC, merged